security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: pseudo

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # ============================================================
        # LOGIN FLUTTER
        # ============================================================
        api_login:
            pattern: ^/api/login_check$
            stateless: true
            provider: app_user_provider

            json_login:
                check_path: /api/login_check
                username_path: username
                password_path: password

                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # ============================================================
        # API PROTEGEE PAR JWT
        # ============================================================
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider

            jwt: ~

        # ============================================================
        # SITE WEB EXISTANT
        # ============================================================
        main:
            lazy: true
            provider: app_user_provider

            custom_authenticator: App\Security\AppCustomAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:

        # Le login Flutter est public
        - { path: ^/api/login_check$, roles: PUBLIC_ACCESS }

        # Le reste de l'API nécessite un JWT
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        # Ton site existant
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

# attention, à remettre

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10